### ISSUE TITLE
crashes after some time

### ISSUE THREAD

**Issue by bjo81** [Zibbp/spotify-playlist-sync#5]
```
1:58PM INF Creating playlist: Erased Tapes Picks  - Our musical highlights of 2024, as selected by the Erased Tapes team.
1:58PM INF fetched 28 tracks from playlist Erased Tapes Picks  platform=spotify
1:58PM INF fetched 0 tracks from playlist Erased Tapes Picks  platform=tidal
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x160 pc=0x732ca8]
goroutine 1 [running]:
github.com/zibbp/spotify-playlist-sync/convert.(*Service).SpotifyToTidal(0x4000209770, 0x1, 0x1, 0x1)
	/app/convert/spotify_tidal.go:159 +0xf68
main.main.func1(0x4000021600?)
	/app/main.go:118 +0x120
github.com/urfave/cli/v2.(*Command).Run(0x40001a8000, 0x4000021600, {0x400010d710, 0x3, 0x3})
	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:279 +0x71c
github.com/urfave/cli/v2.(*Command).Run(0x40001a82c0, 0x4000021540, {0x4000020080, 0x4, 0x4})
	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:272 +0x918
github.com/urfave/cli/v2.(*App).RunContext(0x4000198200, {0xa02d20, 0xd83dc0}, {0x4000020080, 0x4, 0x4})
	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:337 +0x514
github.com/urfave/cli/v2.(*App).Run(...)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:311
main.main()
	/app/main.go:141 +0x530
```

**Comment by Zibbp** [comment]
Not sure if that's related to the track or the local db. Is this the only playlist in the conversion, or did tracks successfully sync previously?

Can you try the `:dev` tag? I made a change to skip empty tracks which might also be the issue.

**Comment by bjo81** [comment]
Other playlists converted successfully. I've removed the playlist now, but I can readd it and try the `:dev` tag

**Comment by bjo81** [comment]
Now some new error:
```
10:42AM INF adding track to tidal playlist spotify_track_id=1Sq7UBCYrhsJqczLOjmq5f spotify_track_name="All That Keeps Us" tidal_playlist_id=38f6d26d-5368-4567-9d04-78d7a1e0bb40 tidal_track_id=25794230

10:42AM INF adding track to tidal playlist spotify_track_id=1Sq7UBCYrhsJqczLOjmq5f spotify_track_name="All That Keeps Us" tidal_playlist_id=38f6d26d-5368-4567-9d04-78d7a1e0bb40 tidal_track_id=25794230

10:42AM DBG Track 25794230 already exists in playlist 38f6d26d-5368-4567-9d04-78d7a1e0bb40

10:42AM ERR error adding track to database spotify_track_id=1Sq7UBCYrhsJqczLOjmq5f spotify_track_name="All That Keeps Us"
```
